# Generated by Django 5.0.6 on 2024-06-22 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('resume', models.BinaryField()),
                ('documents', models.JSONField()),
                ('application_status', models.CharField(max_length=255)),
                ('interview_schedule', models.JSONField()),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobmanagement.jobposting')),
            ],
        ),
    ]
